### ISSUE TITLE
Downloadable version?

### ISSUE THREAD

**Issue by ematta** [chris-martin/extjs-docs#1]
Hey there,

My team is currently stuck with ExtJS 2.2 for the foreseeable future. We found the website, which thank you by the way, but we were wondering if there was a downloadable version of the site so we can save it (in the off chance that github decides to commit seppuku). 

Thanks for considering this

--Enrique

**Comment by chris-martin** [comment]
Hey Enrique - Sincere condolences for your being stuck on Ext 2 :frowning: 

https://chris-martin.github.io/extjs-docs/ is just a static site hosted by GitHub Pages, so the content is all in the `gh-pages` branch of the repo.

```
git clone https://github.com/chris-martin/extjs-docs.git
git checkout gh-pages
```

Since the Ext docs webapp uses ajax, you also need to run a simple web server to use it. For example,

```
python -m SimpleHTTPServer 3000
```

Then you should be able to go to `http://localhost:3000` and view it.

**Comment by ematta** [comment]
Thank you so much. You have our sincere thanks!

**Comment by chris-martin** [comment]
:+1:
